[package]
name = "gerrit"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]

[[bin]]
name = "git-clear"
path = "src/main.rs"

[dependencies]
log = "*"
env_logger = "*"
hyper = "*"
clap = "*"
rustc-serialize = "*"
